Repository essentialkaos/anicorn, pull requests merged in 2018-07, with the labels that each got.

#18 Remove stale PID if process is dead to prevent failure during on Unicorn restarting
  SOURCES/anicorn
  anicorn.spec
Labels: PR • IMPROVEMENT

#19 Version 2.1.5
  .travis.yml
  SOURCES/anicorn
  anicorn.spec
Labels: PR • RELEASE

#20 Fix bug with checking dead process if it is a Unicorn
  SOURCES/anicorn
  anicorn.spec
Labels: PR • FIX

#21 Version 2.1.6
  SOURCES/anicorn
  anicorn.spec
Labels: PR • RELEASE
